#!/bin/bash

function check_ocp() {
    set +e
    oc status &> /dev/null
    res="$?"
    set -e
    OCP="$res"
}

function set_curr_project() {
    if [ "$OCP" -eq 0 ]; then
        orig_project=$(oc project -q)
    fi
}

function restore_curr_project() {
    if [ "$OCP" -eq 0 ]; then
        oc project $orig_project
    fi
}

function go_to_project() {
    if [ "$OCP" -eq 0 ]; then
        set +e
        oc get project $1 &>/dev/null
        if [ "$?" -ne 0 ]; then
            echo "Creating project $1"
            oc new-project $1 &>/dev/null
        else
            echo "Setting project to $1"
            oc project $1 &>/dev/null
        fi
        set -e
    fi
}

function clean_project() {
    if [ "$OCP" -eq 0 ]; then
        set +e
        oc get project $1 &>/dev/null
        if [ "$?" -ne 0 ]; then
            echo "Creating project $1"
            oc new-project $1 &>/dev/null
        else
            echo "Recreating project $1"
	    oc delete project $1 &> /dev/null
	    while true; do
                oc get project $1 &> /dev/null
		if [ "$?" -ne 0 ]; then
		    break
		fi
		sleep 5
	    done
            oc new-project $1 &>/dev/null
        fi
        set -e
    fi
}
