#!/bin/bash
function handle_term {
    local cnt
    local killed=1
    if [ -n "$PID" ]; then
        kill -TERM $PID
        for cnt in {1..10}
        do
            kill -0 $PID >/dev/null 2>&1
            if [ "$?" -ne 0 ]; then
                killed=0
                break
            else
                sleep 1
            fi
        done
        if [ "$killed" -ne 0 ]; then
            kill -9 $PID
        fi
        wait $PID
    fi
    exit 0
}

/opt/peak/run.sh $@ &
PID=$!
wait $PID
exit $?
